_install_update_msg() {
cat <<EOF
To autoload wee-slack on start up, each user will need to symlink the plugin to
the correct autoload folder (depends on your weechat version and configuration):

    \$ ln -s /usr/share/weechat/python/wee_slack.py ~/.weechat/python/autoload/
    \$ ln -s /usr/share/weechat/python/wee_slack.py ~/.local/share/weechat/python/autoload/
EOF
}

post_install() {
  _install_update_msg
}

post_upgrade() {
  _install_update_msg
}
